### ISSUE TITLE
Cannot instantiate Folio catalog links from hash

### ISSUE THREAD

**Issue by justinlittman** [sul-dlss/cocina-models#574] opened 2023-02-21 17:35 UTC
```
Dry::Struct::Error:
       [Cocina::Models::SymphonyCatalogLink.new] "folio" (String) has invalid type for :catalog violates constraints (included_in?(["symphony", "previous symphony"], "folio") failed)
```

**Comment by justinlittman** [comment] 2023-02-21 17:38
See test in https://github.com/sul-dlss/cocina-models/pull/575

cc @mjgiarlo

**Comment by ndushay** [comment] 2023-02-21 18:29
I think the problem is the missing alpha prefix for the folio identifier;  I am closing this ticket per slack conversation with Justin.  Please reopen if I'm wrong.

**Closed by ndushay** 2023-02-21 18:29 UTC
Labels: Folio
